#!/bin/bash

function install_ansible() {
	echo "Установка зависимостей для ansible"
	apt update --yes &&
		apt-get install python3-venv sshpass --yes
	{ python3 -m venv venv &&
		./venv/bin/pip install -r requirements.txt; } >/dev/null
}

function inventory() {
	echo "Конфигурирование inventory.ini"
	read -erp "Введите ip адресс сервера администрирования, должен быть доступен для подключения по ssh (Например: 192.168.122.115): " KSC_IP
	read -erp "Введите имя пользователя для подключения по ssh $KSC_IP (пользователь должен быть в группе sudo) (Например: astra): " KSC_USER
	read -serp "Введите пароль для пользователя $KSC_USER (Например: Qwerty123!): " KSC_SUDO_PASSWORD
	echo -e "Конфигурация для подключения
    ip:$KSC_IP
    user:$KSC_USER"

	cp inventory.ini.sample inventory.ini
	sed -i 's|%KSC_IP%|'"$KSC_IP"'|g' inventory.ini
	sed -i 's|%KSC_USER%|'"$KSC_USER"'|g' inventory.ini
	sed -i 's|%KSC_SUDO_PASSWORD%|'"$KSC_SUDO_PASSWORD"'|g' inventory.ini
}

function ansible_ping() {
	echo "Запущен ansible ping"
	./venv/bin/ansible all -m ping
}

function ansible_playbook() {
	db_type=$(grep '^db_type:' vars.yml | awk -F '"' '{print $2}')
	if [[ "$db_type" == "mysql" ]]; then
		echo "Запущена установка ksc 15 c mariadb"
		rm -rf facts
		./venv/bin/ansible-playbook playbook.yml \
			--tags password \
			--tags apt \
			--tags mdb \
			--tags ksc \
			--tags web \
			--extra-vars @vars.yml || exit 1
	elif [[ "$db_type" == "postgres" ]]; then
		echo "Запущена установка ksc 15 с postgres"
		rm -rf facts
		./venv/bin/ansible-playbook playbook.yml \
			--tags password \
			--tags apt \
			--tags psql \
			--tags ksc \
			--tags web \
			--extra-vars @vars.yml || exit 1
	else
		echo "Укажите тип базы данных (db_type) в vars.yml"
		exit 1
	fi
}

function main() {
	echo "Удаляем предыдущие пакеты"
	apt-get autoremove --purge ksc-web-console --yes
	apt-get autoremove --purge ksc64 --yes
	apt-get autoremove --purge postgresql-14 --yes
	rm -rf /opt/kaspersky
	rm -rf /var/opt/kaspersky
	rm -rf /etc/opt/kaspersky
	rm -rf /var/lib/postgresql
	rm -rf /etc/postgresql/

	install_ansible
	if [ $? -ne 0 ]; then
		echo "Ошибка установки ansible"
		exit 1
	fi

	inventory

	ansible_ping
	if [ $? -ne 0 ]; then
		echo "Невозможно сделать ping для inventory.ini"
		exit 1
	fi

	ansible_playbook

	echo -e "Сохраните данные для подключения:
  $(grep '^db_type:' vars.yml | awk -F '"' '{print $2}'):
    user: root
    password: $(cat facts/db_root_password.txt)
    user: ksc
    password: $(cat facts/ksc_db_password.txt)
  ksc web console/mmc console:
    user: ksc
    password: $(cat facts/ksc_web_password.txt)"

	echo -e "Октройте веб панель по адресу
https://$KSC_IP или https://$KSC_IP:8080
Или подключитесь через mmc консоль"
}

main
